
var tonalidades = {
	"modelo": {
		"1b":{"roman":"Ib", "tri":"" ,"tetra":"7M"},
		"1":{"roman":"I", "tri":"" ,"tetra":"7M"},
		"1#":{"roman":"I#", "tri":"" ,"tetra":"7M"},
		"2b":{"roman":"II", "tri":"m","tetra":"m7"},
		"2":{"roman":"II", "tri":"m","tetra":"m7"},
		"2#":{"roman":"II", "tri":"m","tetra":"m7"},
		"3b":{"roman":"III", "tri":"m","tetra":"m7"},
		"3":{"roman":"III", "tri":"m","tetra":"m7"},
		"3#":{"roman":"III", "tri":"m","tetra":"m7"},
		"4b":{"roman":"IV", "tri":"","tetra":"7M"},
		"4":{"roman":"IV", "tri":"","tetra":"7M"},
		"4#":{"roman":"IV", "tri":"","tetra":"7M"},
		"5b":{"roman":"V", "tri":"","tetra":"7"},
		"5":{"roman":"V", "tri":"","tetra":"7"},
		"5#":{"roman":"V", "tri":"","tetra":"7"},
		"6b":{"roman":"VI", "tri":"m","tetra":"m7"},
		"6":{"roman":"VI", "tri":"m","tetra":"m7"},
		"6#":{"roman":"VI", "tri":"m","tetra":"m7"},
		"7b":{"roman":"VII", "tri":"m5b","tetra":"m5b/7"},
		"7":{"roman":"VII", "tri":"m5b","tetra":"m5b/7"},
		"7#":{"roman":"VII", "tri":"m5b","tetra":"m5b/7"}
		},
	"C": {
		"1b":{"nat":'Cb', alt:'B'},
		"1":{"nat":'C'},
		"1#":{"nat":'C#'},
		"2b":{"nat":'Db'},
		"2":{"nat":'D'},
		"2#":{"nat":'D#'},
		"3b":{"nat":'Eb'},
		"3":{"nat":'E'},
		"3#":{"nat":'E#'},
		"4b":{"nat":'Fb'},
		"4":{"nat":'F'},
		"4#":{"nat":'F#'},
		"5b":{"nat":'Gb'},
		"5":{"nat":'G'},
		"5#":{"nat":'G#'},
		"6b":{"nat":'Ab'},
		"6":{"nat":'A'},
		"6#":{"nat":'A#'},
		"7b":{"nat":'Bb'},
		"7":{"nat":'B'},
		"7#":{"nat":'B#'},
		},
	"C#": {
		"1b":{"nat":'C'},
		"1":{"nat":'C#'},
		"1#":{"nat":'C##', alt:'D'},
		"2b":{"nat":'D'},
		"2":{"nat":'D#'},
		"2#":{"nat":'D##'},
		"3b":{"nat":'E', alt:'F'},
		"3":{"nat":'E#', alt:'F'},
		"3#":{"nat":'E##', alt:'F#'},
		"4b":{"nat":'F'},
		"4":{"nat":'F#'},
		"4#":{"nat":'F##'},
		"5b":{"nat":'G'},
		"5":{"nat":'G#'},
		"5#":{"nat":'G##'},
		"6b":{"nat":'A'},
		"6":{"nat":'A#'},
		"6#":{"nat":'A##'},
		"7b":{"nat":'B'},
		"7":{"nat":'B#', alt:'C'},
		"7#":{"nat":'B##', alt:'C#'},
		},
	"D": {
		"1b":{"nat":'Db'},
		"1":{"nat":'D'},
		"1#":{"nat":'D#'},
		"2":{"nat":'E'},
		"2#":{"nat":'E'},
		"2b":{"nat":'E'},
		"3":{"nat":'F#'},
		"3#":{"nat":'F#'},
		"3b":{"nat":'F#'},
		"4":{"nat":'G'},
		"4#":{"nat":'G'},
		"4b":{"nat":'G'},
		"5":{"nat":'A'},
		"5#":{"nat":'A'},
		"5b":{"nat":'A'},
		"6":{"nat":'B'},
		"6#":{"nat":'B'},
		"6b":{"nat":'B'},
		"7":{"nat":'C#'},
		"7#":{"nat":'C#'},
		"7b":{"nat":'C#'},
		},
	"D#": {
		"1b":{"nat":'D#'},
		"1":{"nat":'D#'},
		"1#":{"nat":'D#'},
		"2b":{"nat":'E#', alt:'F'},
		"2":{"nat":'E#', alt:'F'},
		"2#":{"nat":'E#', alt:'F'},
		"3b":{"nat":'F##', alt:'G'},
		"3":{"nat":'F##', alt:'G'},
		"3#":{"nat":'F##', alt:'G'},
		"4b":{"nat":'G#'},
		"4":{"nat":'G#'},
		"4#":{"nat":'G#'},
		"5b":{"nat":'A#'},
		"5":{"nat":'A#'},
		"5#":{"nat":'A#'},
		"6b":{"nat":'B#', alt:'C'},
		"6":{"nat":'B#', alt:'C'},
		"6#":{"nat":'B#', alt:'C'},
		"7b":{"nat":'C##', alt:'D'},
		"7":{"nat":'C##', alt:'D'},
		"7#":{"nat":'C##', alt:'D'},
		},
	"E": {
		"1b":{"nat":'E'},
		"1":{"nat":'E'},
		"1#":{"nat":'E'},
		"2b":{"nat":'F#'},
		"2":{"nat":'F#'},
		"2#":{"nat":'F#'},
		"3b":{"nat":'G#'},
		"3":{"nat":'G#'},
		"3#":{"nat":'G#'},
		"4b":{"nat":'A'},
		"4":{"nat":'A'},
		"4#":{"nat":'A'},
		"5b":{"nat":'B'},
		"5":{"nat":'B'},
		"5#":{"nat":'B'},
		"6b":{"nat":'C#'},
		"6":{"nat":'C#'},
		"6#":{"nat":'C#'},
		"7b":{"nat":'D#'},
		"7":{"nat":'D#'},
		"7#":{"nat":'D#'},
		},
	"F": {
		"1b":{"nat":'F'},
		"1":{"nat":'F'},
		"1#":{"nat":'F'},
		"2b":{"nat":'G'},
		"2":{"nat":'G'},
		"2#":{"nat":'G'},
		"3b":{"nat":'A'},
		"3":{"nat":'A'},
		"3#":{"nat":'A'},
		"4b":{"nat":'Bb'},
		"4":{"nat":'Bb'},
		"4#":{"nat":'Bb'},
		"5b":{"nat":'C'},
		"5":{"nat":'C'},
		"5#":{"nat":'C'},
		"6b":{"nat":'D'},
		"6":{"nat":'D'},
		"6#":{"nat":'D'},
		"7b":{"nat":'E'},
		"7":{"nat":'E'},
		"7#":{"nat":'E'},
		},
	"F#": {
		"1b":{"nat":'F#'},
		"1":{"nat":'F#'},
		"1#":{"nat":'F#'},
		"2b":{"nat":'G#'},
		"2":{"nat":'G#'},
		"2#":{"nat":'G#'},
		"3b":{"nat":'A#'},
		"3":{"nat":'A#'},
		"3#":{"nat":'A#'},
		"4b":{"nat":'B'},
		"4":{"nat":'B'},
		"4#":{"nat":'B'},
		"5b":{"nat":'C#'},
		"5":{"nat":'C#'},
		"5#":{"nat":'C#'},
		"6b":{"nat":'D#'},
		"6":{"nat":'D#'},
		"6#":{"nat":'D#'},
		"7b":{"nat":'E#', alt:'F'},
		"7":{"nat":'E#', alt:'F'},
		"7#":{"nat":'E#', alt:'F'},
		},

}



var strMusica = "";
function escreveMusica(musica, tom){
	strMusica = "";
	campo = tonalidades[tom];
	musica.forEach(forEachNota);


	return strMusica;
}

function forEachNota(nota, index, arr) {
	notaNoTom = campo[nota]
	strMusica += notaNoTom["nat"];
	if(index < arr.length-1){
		strMusica += " - ";
	}
}


